heat_template_version: newton

description: Template to deploy openshift master nodes

parameters:
  public_net:
    type: string
    label: public net ID
    description: Public network for the node FIPs
  image:
    type: string
    label: Image name or ID
    description: Image to be used for the kuryr nodes
  flavor:
    type: string
    label: Flavor
    description: Flavor to be used for the image
    default: m1.small
  key:
    type: string
    label: key name
    description: Keypair to be used for the instance
  private_key:
    type: string
    label: key content to access other nodes
    description: private key to configure all nodes
  vm_net:
    type: string
    label: VM Network
    description: Neutron network for VMs
  vm_subnet:
    type: string
    label: VM Subnet
    description: Neutron subnet for VMs
  k8s_lb_pool:
    type: string
    label: K8s Pool
    description: K8s LoadBalancer Pool
  k8s_api_sg:
    type: string
    label: kubernetes API sg
    description: Security Group for Kubernetes API
  name:
    type: string
    label: Instance name
    description: Master node instance name

resources:
  instance_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: vm_net }
      security_groups:
        - default
        - { get_param: k8s_api_sg }
      fixed_ips:
        - subnet: { get_param: vm_subnet }

  instance_fip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: instance_port }

  instance:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - port: { get_resource: instance_port }
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            __privkey__: { get_param: private_key }
          template: |
            #!/bin/bash
            set -ex

            # Deps for openshift-ansible
            yum install -y epel-release
            yum install -y ansible git
            git clone https://github.com/celebdor/openshift-ansible /home/centos/openshift-ansible
            pushd /home/centos/openshift-ansible
            git checkout kuryr_rebase
            popd
            chown centos:centos -R /home/centos/openshift-ansible
            mkdir -p /home/centos/.ssh
            cat > /home/centos/.ssh/id_rsa <<EOF
            __privkey__
            EOF


  lb_member:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: { get_param: k8s_lb_pool }
      protocol_port: 8443
      address: { get_attr: [instance, first_address]}
      subnet: { get_param: vm_subnet }

outputs:
  instance_fip:
    description: FIP address of the worker node
    value: { get_attr: [instance_fip, floating_ip_address] }
