parameters:
  image: centos7
  master_flavor: m1.medium
  worker_flavor: m1.large
  public_net: public
  vm_net_cidr: 10.11.0.0/24
  vm_net_gateway: 10.11.0.1
  pod_net_cidr: 10.10.0.0/16
  pod_net_gateway: 10.10.0.1
  service_net_cidr: 172.30.0.0/16
  service_net_gateway: 172.30.255.254
  service_router_port_ip: 172.30.255.254
  service_lbaas_ip: 172.30.0.1
  external_dns_server: 10.12.70.62
  dns_domain: kuryrscale
  master_num: 1
  worker_num: 3
  subports_per_pool: 5

resource_registry:
  OS::Kuryr::PodInVMNetworking: networking_deployment.yaml
  OS::Kuryr::SegIds: seg_ids.yaml
  OS::Kuryr::Subports: subports.yaml
