heat_template_version: pike

description: Template to create subports

parameters:
  network:
    type: string
    label: Subport Network
  subnet:
    type: string
    label: Subport Subnet
  pod_access_sg:
    type: string
    label: Pod access sg

resources:
  subports:
    type: OS::Neutron::Port
    properties:
      network: { get_param: network }
      security_groups:
        - default
        - { get_param: pod_access_sg }
      fixed_ips:
        - subnet: { get_param: subnet }

outputs:
  subport_id:
    value: { get_resource: subports }
