heat_template_version: 2014-10-16

description: Template to deploy openshift worker nodes

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for the kuryr nodes
  flavor:
    type: string
    label: Flavor
    description: Flavor to be used for the image
    default: m1.small
  key:
    type: string
    label: key name
    description: Keypair to be used for the instance
  trunk_port:
    type: string
    label: Trunk Port
    description: Neutron Trunk Port for VMs

resources:
  instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - port: { get_param: trunk_port }
